---
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'feat'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
  - title: '📊 Monitoring & Metrics'
    labels:
      - 'monitoring'
      - 'metrics'
      - 'prometheus'
      - 'grafana'
  - title: '🔒 Security'
    labels:
      - 'security'
      - 'vulnerability'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'docs'
      - 'ci'
      - 'build'
      - 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

  ## 🐳 Docker Images
  
  - **Docker Hub**: `magicalyak/transmissionvpn:$NEXT_PATCH_VERSION`
  - **GitHub Container Registry**: `ghcr.io/magicalyak/transmissionvpn:$NEXT_PATCH_VERSION`
  - **Multi-Architecture**: `linux/amd64`, `linux/arm64`

  ## 📊 Monitoring
  
  This release includes enhanced monitoring capabilities with Prometheus metrics and Grafana dashboards.

  **Full Changelog**: https://github.com/${{ github.repository }}/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION 