apiVersion: 1

datasources:
  - name: InfluxDB2
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: transmissionvpn
      defaultBucket: metrics
      tlsSkipVerify: true
    secureJsonData:
      token: transmissionvpn-super-secret-token
    editable: true 