global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'transmissionvpn'
    static_configs:
      - targets: ['transmissionvpn:9099']
    scrape_interval: 15s
    metrics_path: /metrics 