---
name: "🐛 Bug Report"
description: "Submit a bug report to help us improve."
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to this project!

        - **Are you having an issue with the container not starting, VPN connection, or IP leaks?**
          Please use the 🔎 **Support Request** form instead.
        - **Have you checked for similar issues?**
          There might be an existing solution.

        Please be as detailed as possible in your report.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      description: "Please confirm the following before submitting a new issue."
      options:
        - label: >-
            I have checked the [troubleshooting
            guide](https://github.com/magicalyak/transmissionvpn/blob/main/docs/TROUBLESHOOTING.md)
            and known issues.
          required: true
        - label: >-
            I have searched for similar issues and have not found an existing
            solution.
          required: true
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: >-
        A clear and concise description of what the bug is.
      placeholder: >-
        e.g., "The container fails to start when using PIA and WireGuard."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Please provide the exact steps to reproduce the behavior."
      placeholder: |
        1. Set `VPN_PROVIDER` to `pia`.
        2. Set `VPN_CLIENT` to `wireguard`.
        3. Run `docker-compose up`.
        4. See error in logs.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Container Logs"
      description: >-
        Please provide the full, unredacted container logs.
      placeholder: |
        <details>
        <summary>Click to expand</summary>

        ```
        <your logs here>
        ```
        </details>
      render: bash
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: "Environment"
      description: >-
        Please provide your `.env` file, with any sensitive information
        redacted.
      placeholder: |
        <details>
        <summary>Click to expand</summary>

        ```
        VPN_PROVIDER=pia
        VPN_CLIENT=wireguard
        # ...
        ```
        </details>
      render: bash
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Container Version"
      description: "What version of the container are you running?"
      placeholder: "e.g., `latest` or `4.0.5-1`"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: "What operating system is your Docker host running on?"
      options:
        - "Linux"
        - "macOS"
        - "Windows"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: >-
        Add any other context about the problem here (e.g., screenshots,
        related issues). 