---
name: "🚀 Feature Request"
description: "Suggest a new feature or enhancement."
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature!

        - **Is this a bug or a support question?**
          Please use the appropriate form for those.
        - **Is your feature request related to a problem?**
          Please describe the problem you're trying to solve.

        Your feedback is valuable in shaping the future of this project.
  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      description: >-
        Please provide a clear and concise description of the feature you
        are requesting.
      placeholder: >-
        e.g., "Add support for a new alternative web UI called '...'."
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: "Problem or Use Case"
      description: >-
        What problem does this feature solve? Why is it needed?
      placeholder: >-
        e.g., "I am always frustrated when [...] because [...]."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: >-
        Describe the solution you'd like.
        How do you see this feature being implemented?
      placeholder: |
        - Add a new environment variable `...`
        - Modify the script `...` to handle the new option.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: >-
        Have you considered any alternative solutions or workarounds?
      placeholder: >-
        e.g., "I have tried [...] but it only works partially because [...]."
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: "Additional Information"
      description: >-
        Is there anything else we should know?
        (e.g., links to related projects, screenshots, mockups) 