---
name: "🔎 Support Request"
description: >-
  Get help with container startup, VPN issues, or general questions.
labels: ["support", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Welcome! Please provide the following details to help us resolve
        your issue.

        - **Is this a bug or a feature request?**
          Please use the appropriate form for those.
        - **Have you checked the documentation?**
          The [README](https://github.com/magicalyak/transmissionvpn) and
          [troubleshooting guide](https://github.com/magicalyak/transmissionvpn/blob/main/docs/TROUBLESHOOTING.md)
          have answers to common questions.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      description: "Please confirm you've completed these steps."
      options:
        - label: >-
            I have checked the [troubleshooting
            guide](https://github.com/magicalyak/transmissionvpn/blob/main/docs/TROUBLESHOOTING.md)
            for a solution.
          required: true
        - label: >-
            I have searched for similar issues and found none that are open
            or closed.
          required: true
        - label: >-
            I am running the latest version of the container.
          required: true
  - type: textarea
    id: problem-description
    attributes:
      label: "Problem Description"
      description: >-
        Please provide a clear and concise description of the problem.
      placeholder: |
        e.g.,
        - The container fails to start with the error message "..."
        - I'm unable to connect to the web UI.
        - My external IP address is not my VPN's IP.
    validations:
      required: true
  - type: textarea
    id: docker-config
    attributes:
      label: "Docker Configuration"
      description: |
        Please share your `docker-compose.yml` or `docker run` command.
        **IMPORTANT:** Redact any sensitive information like passwords.
      placeholder: |
        ```yaml
        version: "3.8"
        services:
          transmissionvpn:
            image: magicalyak/transmissionvpn:latest
            ...
        ```
      render: yaml
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Container Logs"
      description: |
        Please provide the full container logs.
        Run `docker logs transmissionvpn` to get the logs.
      placeholder: |
        ```
        <PASTE LOGS HERE>
        ```
      render: shell
    validations:
      required: true
  - type: input
    id: image-version
    attributes:
      label: "Image Version"
      description: "What version of the Docker image are you using?"
      placeholder: "e.g., latest, 4.0.5-r0"
    validations:
      required: true
  - type: dropdown
    id: vpn-provider
    attributes:
      label: "VPN Provider"
      description: "Which VPN provider are you using?"
      options:
        - "NordVPN"
        - "ExpressVPN"
        - "Surfshark"
        - "ProtonVPN"
        - "Private Internet Access"
        - "PrivadoVPN"
        - "Mullvad"
        - "Other"
    validations:
      required: true
  - type: dropdown
    id: vpn-client
    attributes:
      label: "VPN Client"
      description: "Which VPN client are you using?"
      options:
        - "OpenVPN"
        - "WireGuard"
      default: 0
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: "Additional Information"
      description: >-
        Is there anything else we should know?
        (e.g., host OS, Docker version, network setup) 