name: ❓ Support & Questions
description: Get help with configuration or ask questions about transmissionvpn
title: "[SUPPORT] "
labels:
  - question
  - support

body:
  - type: markdown
    attributes:
      value: |
        Need help with transmissionvpn? Please provide details about your setup and what you're trying to achieve.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before asking for support
      options:
        - label: I have read the README.md and EXAMPLES.md documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What kind of help do you need?
      options:
        - Configuration Help
        - VPN Setup Issues
        - Performance Questions
        - Integration with Other Services
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: what-trying-to-achieve
    attributes:
      label: What are you trying to achieve?
      description: Describe your goal or what you want to accomplish
      placeholder: "I want to... I'm trying to set up..."
    validations:
      required: true

  - type: textarea
    id: current-setup
    attributes:
      label: Current Setup
      description: Share your current docker-compose.yml or docker run command
      placeholder: |
        ```yaml
        # Your current configuration
        ```
      render: yaml

  - type: dropdown
    id: vpn-provider
    attributes:
      label: VPN Provider
      description: Which VPN service are you using?
      options:
        - NordVPN
        - ExpressVPN
        - Surfshark
        - ProtonVPN
        - Mullvad
        - Private Internet Access (PIA)
        - CyberGhost
        - IPVanish
        - Custom/Self-hosted
        - Other
        - Not using VPN

  - type: textarea
    id: specific-problem
    attributes:
      label: Specific Problem or Question
      description: What specific issue are you encountering or question do you have?
      placeholder: "When I try to... I get... How do I..."
    validations:
      required: true

  - type: textarea
    id: what-tried
    attributes:
      label: What have you tried?
      description: What troubleshooting steps or configurations have you already attempted?
      placeholder: |
        1. I tried...
        2. I also attempted...
        3. I checked...

  - type: textarea
    id: environment-details
    attributes:
      label: Environment Details
      description: Please share relevant system information
      placeholder: |
        - OS: (e.g., Ubuntu 22.04, macOS Monterey, Windows 11)
        - Docker version: 
        - Docker Compose version: 
        - Architecture: (e.g., x86_64, arm64)
        - NAS/Platform: (e.g., Synology, QNAP, Unraid)

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs (if applicable)
      description: Include any error messages or relevant logs
      placeholder: |
        ```
        # Paste relevant logs here
        # Remove sensitive information
        ```
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: "Network setup, firewall rules, other services running..." 