global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # Add any rule files here
  # - "alert-rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # TransmissionVPN custom metrics server (single container solution)
  - job_name: 'transmissionvpn'
    static_configs:
      - targets: ['transmissionvpn:9099']  # Use container name if on same Docker network
      # Alternative for external access:
      # - targets: ['rocky.gamull.com:9099']  # Use your server hostname/IP
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: true

  # TransmissionVPN health endpoint (comprehensive health data)
  - job_name: 'transmissionvpn-health'
    static_configs:
      - targets: ['transmissionvpn:9099']  # Same server, different endpoint
      # Alternative for external access:
      # - targets: ['rocky.gamull.com:9099']
    scrape_interval: 60s
    scrape_timeout: 15s
    metrics_path: /health
    honor_labels: true

  # Example: Add your own services here
  # - job_name: 'my-other-service'
  #   static_configs:
  #     - targets: ['my-service:8080'] 