global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  - job_name: 'transmission-exporter'
    static_configs:
      - targets: ['transmission-exporter:19091']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  - job_name: 'transmission-direct'
    static_configs:
      - targets: ['transmissionvpn:9091']
    scrape_interval: 60s
    metrics_path: /transmission/rpc
    params:
      method: ['session-stats']
    scrape_timeout: 30s

  - job_name: 'blackbox-vpn'
    static_configs:
      - targets:
        - http://checkip.amazonaws.com
        - https://api.ipify.org
        - https://icanhazip.com
    metrics_path: /probe
    params:
      module: [http_2xx]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-exporter'
    static_configs:
      - targets: ['blackbox-exporter:9115']
    scrape_interval: 30s 