version: '3.8'

services:
  influxdb2:
    image: influxdb:2.7
    container_name: influxdb2
    ports:
      - "${INFLUXDB_PORT:-8086}:8086"
    volumes:
      - influxdb2_data:/var/lib/influxdb2
      - influxdb2_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password123}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-transmissionvpn}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-metrics}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-my-super-secret-auth-token}
    networks:
      - monitoring
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
    environment:
      - HOST_ETC=/host/etc
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_MOUNT_PREFIX=/host
    networks:
      - monitoring
    depends_on:
      - influxdb2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-influx
    ports:
      - "3001:3000"
    volumes:
      - grafana_influx_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=${GRAFANA_ALLOW_SIGN_UP:-false}
      - GF_PROVISIONING_ENABLED=true
    networks:
      - monitoring
    restart: unless-stopped

  transmission-metrics:
    image: python:3.9-slim
    container_name: transmission-metrics
    volumes:
      - ./scripts/transmission_metrics.py:/app/transmission_metrics.py
    working_dir: /app
    command: >
      sh -c "pip install requests influxdb-client && python transmission_metrics.py"
    environment:
      - TRANSMISSION_HOST=${TRANSMISSION_HOST:-transmissionvpn}
      - TRANSMISSION_PORT=${TRANSMISSION_PORT:-9091}
      - INFLUXDB_URL=http://influxdb2:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-my-super-secret-auth-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-transmissionvpn}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-metrics}
    networks:
      - monitoring
    depends_on:
      - influxdb2
    restart: unless-stopped

volumes:
  influxdb2_data:
  influxdb2_config:
  grafana_influx_data:

networks:
  monitoring:
    driver: bridge
  default:
    external:
      name: ${TRANSMISSIONVPN_NETWORK:-transmissionvpn_default} 