---
name: "CodeQL Security Scan"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '30 2 * * 1' # Run every Monday at 2:30 AM

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['python']
        # Only analyzing languages that are actually present in the repository.
        # CodeQL will automatically detect and analyze shell scripts.

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Initialize CodeQL"
        uses: github/codeql-action/init@v3
        with:
          languages: python
          # Uncomment the following line if you want to use custom queries.
          # queries: security-extended,security-and-quality

      - name: "Autobuild"
        uses: github/codeql-action/autobuild@v3

      - name: "Perform CodeQL Analysis"
        uses: github/codeql-action/analyze@v3 